apiVersion: v1
kind: Service # headless service for dns routing directly to pods for a statefulset
metadata:
  name: postgres-headless-service
  labels:
    app: postgres
spec:
  clusterIP: None # explicilty set to None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    # statefulset only allows rollingupdate
  serviceName: "postgres-headless-service" # need to specifiy the headless service
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432 # default port for the container
          name: postgres
        env:
        - name: POSTGRES_USER # create a nondefault user
          value: "not_default_postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_DB # name the database in postgres
          value: "non_default_postgres"
        volumeMounts:
        - name: postgres-storage # must match volumeClaimTemplates.metadata.name
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage # must match volumeMounts.name
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - port: 5432 # Port used internally by other cluster services
    targetPort: 5432 # Port the PostgreSQL container is listening on
    nodePort: 30432 # External port opened on every Kubernetes node
